# Configuración de la conexión a PostgreSQL 
quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=tu_usuario 
quarkus.datasource.password=tu_contraseña 
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/
#tu_base_de_datos # Habilitar el uso de Hibernate ORM
quarkus.hibernate-orm.database.generation=update 
quarkus.hibernate-orm.log.sql=true
 